version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - POSTGRES_USER=fernando
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=client_registration_db
      - DB_PORT=5432
      - API_PORT=3000
      - SECRET_KEY=arsene_lupin
      - NODE_ENV=docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=fernando
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=client_registration_db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U fernando -d client_registration_db"
        ]
      interval: 7s
      timeout: 4s
      retries: 5
      start_period: 5s

  migration:
    build: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "db:5432",
        "--",
        "yarn",
        "migrate"
      ]
    links:
      - db
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
